// singles.js — 26 posteos de imagen única (no carrusel).
// Formato: título grande + mensaje + CTA "Escribinos". Temas: dark / light / magenta (#CC007E + letra negra).
module.exports = [
  { id: 1, theme: 'dark', title: 'El Excel no cierra la caja', msg: 'Vos sí. Con un sistema, el cierre del día es cosa de minutos.', cta: 'Escribinos y te mostramos cómo' },
  { id: 2, theme: 'light', title: '¿Sabés cuánto vendiste ayer?', msg: 'Respondé sin mirar. Si dudaste, es hora de ordenar los números.', cta: 'Escribinos y lo ordenamos' },
  { id: 3, theme: 'magenta', title: 'Un error de tipeo cuesta más que un sistema', msg: 'La falta, la deuda olvidada y el stock que no cierra se pagan solos.', cta: 'Escribinos y empezá hoy' },
  { id: 4, theme: 'dark', title: 'Los papeles no avisan', msg: 'Tu sistema sí: stock, deudas y reportes, siempre al día.', cta: 'Escribinos' },
  { id: 5, theme: 'light', title: '3 cosas que tu libreta no te dice', msg: 'Lo que te deben, lo que falta en stock y lo que perdés cada día.', cta: 'Escribinos y te mostramos' },
  { id: 6, theme: 'magenta', title: 'La caja cierra sola', msg: 'Cuando el sistema trabaja por vos, el cierre son 5 minutos.', cta: 'Escribinos' },
  { id: 7, theme: 'dark', title: 'Stock que no ves, plata que no cobrás', msg: 'El inventario al día es la diferencia entre adivinar y saber.', cta: 'Escribinos y lo ponemos en orden' },
  { id: 8, theme: 'magenta', title: 'Cerrar la caja en 5 minutos', msg: 'Con sistema. Sin papelitos, sin sumar de memoria.', cta: 'Escribinos y probalo' },
  { id: 9, theme: 'light', title: 'Tu cliente no espera', msg: 'Tu sistema tampoco: respuestas al instante, ventas que no se pierden.', cta: 'Escribinos' },
  { id: 10, theme: 'dark', title: 'El cuaderno es gratis', msg: 'Hasta que perdés la primera venta. O la primera deuda.', cta: 'Escribinos y empezá' },
  { id: 11, theme: 'magenta', title: 'Deudores: la plata que más trabajo te da cobrar', msg: 'Con recordatorios automáticos, cobrás sin perseguir a nadie.', cta: 'Escribinos' },
  { id: 12, theme: 'light', title: 'Un sistema no es un gasto', msg: 'Es un empleado que nunca se enferma, no pide vacaciones y nunca se olvida.', cta: 'Escribinos y te contamos' },
  { id: 13, theme: 'dark', title: 'Mientras dormís, tu WhatsApp puede vender', msg: 'Catálogo, pedidos y cobro por mensaje, conectados a tu sistema.', cta: 'Escribinos' },
  { id: 14, theme: 'magenta', title: 'El ticket, el stock y la caja', msg: 'Tres lugares, un solo problema. Un solo sistema, una sola solución.', cta: 'Escribinos y lo resolvemos' },
  { id: 15, theme: 'light', title: 'Orden no es lujo', msg: 'Es lo que hace crecer: datos claros, decisiones rápidas.', cta: 'Escribinos' },
  { id: 16, theme: 'dark', title: 'Tu memoria no escala', msg: 'Si los números solo viven en tu cabeza, el negocio crece hasta ahí.', cta: 'Escribinos y lo pasamos a un sistema' },
  { id: 17, theme: 'magenta', title: 'La primera reunión no cuesta nada', msg: 'El desorden cuesta todos los días. Empezá por una charla sin cargo.', cta: 'Escribinos y coordinamos' },
  { id: 18, theme: 'light', title: 'Del cuaderno a la pantalla', msg: 'En 4 pasos: reunión, propuesta, instalación y acompañamiento.', cta: 'Escribinos' },
  { id: 19, theme: 'dark', title: 'Vos sos el dueño de tus datos', msg: 'Siempre. Backups incluidos y exportación libre cuando quieras.', cta: 'Escribinos' },
  { id: 20, theme: 'magenta', title: 'Tu negocio, ordenado', msg: 'Tu información, al alcance de la mano.', cta: 'Escribinos y empezá hoy' },
  { id: 21, theme: 'light', title: 'Vender online sin dejar el mostrador', msg: 'Tu tienda propia, integrada con tu stock y tus precios.', cta: 'Escribinos y te mostramos' },
  { id: 22, theme: 'dark', title: 'Lo que NO hacemos', msg: 'No te vendemos funciones que no vas a usar, ni letra chica, ni desaparecemos.', cta: 'Escribinos' },
  { id: 23, theme: 'magenta', title: 'Tu sistema puede cobrar por vos', msg: 'Deuda por cliente, recordatorios automáticos y menos perseguir.', cta: 'Escribinos' },
  { id: 24, theme: 'dark', title: 'Del cuaderno a la pantalla en 4 pasos', msg: 'Reunión, propuesta, instalación y acompañamiento mensual.', cta: 'Escribinos y coordinamos la primera' },
  { id: 25, theme: 'light', title: '4 señales de que necesitás un sistema', msg: 'Si te pasan 2 o más, tu negocio te está pidiendo orden.', cta: 'Escribinos y agendamos' },
  { id: 26, theme: 'magenta', title: '¿Qué te cuesta más?', msg: 'A) Stock · B) Cobranza · C) Turnos · D) Facturación. Respondé con la letra.', cta: 'Escribinos y lo resolvemos' }
];