// singles-v2.js — títulos más cortos y catchy para los singles 1–38. singles-v2 pisa solo `title` (y badge/ghost si se indica).
// build-singles.js aplica este overlay por id sobre singles.js / singles-backlog.js.
module.exports = {
  1:  { title: ['EXCEL', '<mag>NO CIERRA</mag>', 'LA CAJA.', '<teal>VOS SÍ.</teal>'] },
  2:  { title: ['¿VENDISTE', '<mag>AYER</mag>?', '¿SEGURO?'] },
  3:  { title: ['UN TIPEO', 'CUESTA MÁS QUE', '<mag>UN SISTEMA</mag>'] },
  4:  { title: ['EL PAPEL', 'NO AVISA.', '<teal>EL SISTEMA SÍ.</teal>'] },
  5:  { title: ['LO QUE TU', 'LIBRETA', '<mag>NO TE DICE</mag>'] },
  6:  { title: ['LA CAJA', 'SE CIERRA', '<teal>SOLA</teal>'] },
  7:  { title: ['STOCK INVISIBLE,', 'PLATA <mag>PERDIDA</mag>'] },
  8:  { title: ['CAJA CERRADA', 'EN <mag>5 MIN</mag>'] },
  9:  { title: ['TU CLIENTE', '<mag>NO ESPERA</mag>'] },
  10: { title: ['EL CUADERNO', 'ES GRATIS.', '<teal>HASTA QUE FALLA.</teal>'] },
  11: { title: ['COBRAR', 'SIN <mag>PERSEGUIR</mag>'] },
  12: { title: ['EL EMPLEADO', 'QUE <teal>NUNCA</teal>', 'FALTA'] },
  13: { title: ['VENDÉ', 'MIENTRAS', '<teal>DORMÍS</teal>'] },
  14: { title: ['TICKET. STOCK.', 'CAJA.', '<mag>UN SOLO</mag> SISTEMA'] },
  15: { title: ['ORDEN:', '<mag>NO ES LUJO</mag>'] },
  16: { title: ['TU CABEZA', '<mag>NO ESCALA</mag>'] },
  17: { title: ['LA 1ª CHARLA', '<teal>ES GRATIS</teal>'] },
  18: { title: ['DEL CUADERNO', 'A LA <mag>PANTALLA</mag>'] },
  19: { title: ['TUS DATOS.', '<teal>TUYOS.</teal>'] },
  20: { title: ['NEGOCIO', '<teal>EN ORDEN</teal>'] },
  21: { title: ['ONLINE', 'SIN SOLTAR', '<mag>EL MOSTRADOR</mag>'] },
  22: { title: ['SIN LETRA CHICA.', 'SIN <mag>HUMO</mag>.'] },
  23: { title: ['QUE TE', '<mag>PAGUEN</mag>', 'SOLOS'] },
  24: { title: ['4 PASOS.', 'CERO', '<teal>DRAMA.</teal>'] },
  25: { title: ['¿4 SEÑALES?', '¿TE PASAN', '<mag>2 O MÁS</mag>?'] },
  26: { title: ['¿QUÉ TE', 'CUESTA', '<mag>MÁS</mag>?'] },
  27: { title: ['¿COMPRASTE', '<mag>LO QUE YA</mag>', 'TENÍAS?'] },
  28: { title: ['«HAY STOCK».', '¿<mag>SEGURO</mag>?'] },
  29: { title: ['LA CAJA', 'NO CIERRA.', '<teal>¿OTRA VEZ?</teal>'] },
  30: { title: ['$100.000', 'NO SIEMPRE ES', '<mag>$100.000</mag>'] },
  31: { title: ['«LA SEMANA', 'QUE PASO».', 'PASÓ <mag>UN MES</mag>.'] },
  32: { title: ['«¿Y MI', 'PEDIDO?»', '<teal>YA NO.</teal>'] },
  33: { title: ['CAMBIÁ EL PRECIO', '<teal>UNA SOLA VEZ</teal>'] },
  34: { title: ['AVISÁ 24 HS', 'ANTES.', '<mag>SALVÁ EL TURNO</mag>'] },
  35: { title: ['VUELVE Y', 'NO SABÉS', '<teal>QUÉ LE HICISTE</teal>'] },
  36: { title: ['REGLAS CLARAS.', '<mag>CERO</mag> ÓRDENES', 'VERBALES.'] },
  37: { title: ['¿QUÉ REPETÍS', '<mag>CADA DÍA</mag>?'] },
  38: { title: ['¿IA PARA TODO?', '<teal>NO. AUTOMATIZÁ</teal>', '<teal>LO REPETIDO.</teal>'] }
};
